// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface StoryblokCollapsible {
  label?: string;
  content?: (
    | StoryblokCollapsible
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokHeader
    | StoryblokNavItem
    | StoryblokPage
    | StoryblokProduct
    | StoryblokTeaser
  )[];
  component: "collapsible";
  _uid: string;
}

export interface StoryblokFeature {
  name?: string;
  component: "feature";
  _uid: string;
}

export interface StoryblokGrid {
  columns?: (
    | StoryblokCollapsible
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokHeader
    | StoryblokNavItem
    | StoryblokPage
    | StoryblokProduct
    | StoryblokTeaser
  )[];
  component: "grid";
  _uid: string;
}

export interface StoryblokHeader {
  links?: StoryblokNavItem[];
  component: "header";
  _uid: string;
}

export interface StoryblokNavItem {
  label?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "nav-item";
  _uid: string;
}

export interface StoryblokPage {
  body?: (
    | StoryblokCollapsible
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokHeader
    | StoryblokNavItem
    | StoryblokPage
    | StoryblokProduct
    | StoryblokTeaser
  )[];
  component: "page";
  _uid: string;
}

export interface StoryblokProduct {
  image?: StoryblokAsset;
  description?: string;
  component: "product";
  _uid: string;
}

export interface StoryblokTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
}

export type ContentType = StoryblokPage;
