// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink } from '../storyblok.d.ts';
export interface StoryblokFeature {
  name?: string;
  component: "feature";
  _uid: string;
}

export interface StoryblokGrid {
  columns?: (StoryblokFeature | StoryblokGrid | StoryblokHeader | StoryblokNavItem | StoryblokPage | StoryblokTeaser)[];
  component: "grid";
  _uid: string;
}

export interface StoryblokHeader {
  links?: StoryblokNavItem[];
  component: "header";
  _uid: string;
}

export interface StoryblokNavItem {
  label?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "nav-item";
  _uid: string;
}

export interface StoryblokPage {
  body?: (StoryblokFeature | StoryblokGrid | StoryblokHeader | StoryblokNavItem | StoryblokPage | StoryblokTeaser)[];
  component: "page";
  _uid: string;
}

export interface StoryblokTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
}

export type ContentType = StoryblokPage;
